name: ape_manager_front
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  url_launcher: ^6.0.9
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  device_info_plus: ^9.1.2
  universal_html: ^2.2.4
  sticky_footer_scrollview: ^1.1.1
  intl: ^0.17.0
  sticky_headers: ^0.3.0
  go_router: ^7.1.1
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/logoEcole.png
    - assets/images/APELogo.png
    - assets/images/casiers.jpg
    - assets/images/ecole.jpg
    - assets/images/colis.jpg
    - .env
